sudo: false
language: java


jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
install: true

script: "mvn clean install -DskipTests=true -Dpmd.skip=true -B -V -e"

# for sonarcloud.io
dist: trusty

after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

# use latest java version available instead of travis default
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "legaldocml"
      token:
        secure: $SONAR_TOKEN